// MoE SHAPE BAND perf sweep for every low-bit format [box-only]. Separate from test_lowbit_grouped on purpose: mixing a
// timing lambda into a correctness harness is how a sweep once came to time a different tile than the one it checked.
//
// THIS FILE IS ONLY THE BAND AND THE VERDICT. The sweep rows live in moe_bench_<format>[_wn<N>].cu, one translation unit
// each, because every row is a kernel instantiation and one .cu is one serial hgcc invocation -- see lowbit_moe_bench.hpp
// for why that is the only way to instantiate more and wait less.
//
// WHY THE DENSE WINNER CANNOT BE INHERITED. On dense M=2048 all six formats peak at (64,128,64) w64x64 s2, and TN=128
// wins there because it halves A's re-read count -- the tile was selected by A TRAFFIC. In MoE the bottleneck is the
// WEIGHTS, and the recorded rule is to minimise the TOTAL m-tile count, which favours LARGE TileM. Those point opposite
// ways. But large TileM also wastes rows: at ~128 rows per expert, TM=256 leaves half of every expert's single m-tile
// MASKED. So the question is not "which tile is fastest" but WHICH OF THE TWO EFFECTS DOMINATES, and the honest
// instrument prints both quantities next to the time instead of asserting one of them:
//
//     m_tiles     = sum_e ceil(me[e]/TM)      what the weight-bound rule says to minimise
//     masked_frac = 1 - sum_e me[e] / (TM * m_tiles)      what large TileM costs in wasted rows
//
// MFU is computed on the REAL rows (2 * total_rows * N * K), not on the padded m-tile area, so a configuration cannot
// buy MFU by wasting work.
//
//   Build: TARGET=test_lowbit_moe_bench ./build.sh    (PPU_DEFS=PPU_B_CHUNK=1 -- and CHECK the verified line)
//          add MOE_TK=128 to PPU_DEFS for the TileK=128 half; TileK is a build knob because it changes the per-plane
//          fold factor, so sweeping it at runtime would mean packing every row twice.
//   Run:   ./<bin> [L] [rows_per_expert] [N] [K] [gs] [mode 0|1|2]
#include "lowbit_moe_bench.hpp"
// GENERATED by CMakeLists: MOE_UNIT_COUNT, one declaration per shape, and moe_run_all().
#include "moe_bench_units.inc"

// PPU_CHUNK_STR comes from lowbit_moe_bench.hpp, where every sweep TU also prints its own copy of it.

int main(int argc, char** argv) {
  Band bd{};
  bd.L    = argc > 1 ? atoi(argv[1]) : 64;
  bd.Rows = argc > 2 ? atoi(argv[2]) : 128;
  bd.N    = argc > 3 ? atoi(argv[3]) : 2048;
  bd.K    = argc > 4 ? atoi(argv[4]) : 2048;
  bd.gs   = argc > 5 ? atoi(argv[5]) : 32;
  // SKEWED IS THE DEFAULT. Uniform row counts are the case that teaches least: every expert has the same m-tile count,
  // so there is no masking, no load imbalance, and no tail -- i.e. none of what makes MoE different from a batched
  // GEMM. Real row counts come from a router. mode 0 (uniform) is kept only as a control, and mode 1 exists to be
  // pointed at: its counts are all multiples of TileM, so it never enters the masked path at all.
  bd.mode = argc > 6 ? atoi(argv[6]) : 2;
  bd.scale_k = bd.K / bd.gs;

  // ROW-COUNT DISTRIBUTION. The first ragged generator was (Rows/2)*((e%4)+1) -- 64, 128, 192, 256. Every count a
  // multiple of 64, hence a multiple of every TileM being swept, hence **the masked path was never entered at all**.
  // That is the same mistake as a probe whose period aliases the displacement it is hunting, in different clothing: a
  // "ragged" model whose raggedness is invisible to the thing under test measures the uniform case twice.
  //
  // Real MoE row counts come from a router, so mode 2 gives: arbitrary counts (not multiples of anything), a heavy tail
  // (one expert several times the mean), and ZERO-ROW experts, which are common at small batch and are their own path --
  // filter_and_run has to skip them rather than launch an empty tile.
  bd.me.resize(bd.L); bd.offs.resize(bd.L);
  int zeros = 0, mn = 1 << 30;
  bd.total = 0; bd.Mmax = 0; bd.active = 0;
  for (int e = 0; e < bd.L; ++e) {
    if (bd.mode == 0)      bd.me[e] = bd.Rows;
    else if (bd.mode == 1) bd.me[e] = (bd.Rows / 2) * ((e % 4) + 1);
    else {
      // skewed: ~12% of experts get nothing, one in eight gets a heavy share, the rest scatter around the mean
      const unsigned h = (unsigned)(e * 2654435761u) >> 13;
      if ((h % 8) == 0)      bd.me[e] = 0;
      else if ((h % 8) == 1) bd.me[e] = int(bd.Rows * 3 + (h % 37));                          // heavy tail
      else                   bd.me[e] = int(bd.Rows / 2 + (h % (unsigned)(bd.Rows + 1)));      // not a multiple of TM
    }
    if (bd.me[e] == 0) ++zeros; else ++bd.active;
    mn = std::min(mn, bd.me[e]);
    bd.offs[e] = bd.total; bd.total += bd.me[e]; bd.Mmax = std::max(bd.Mmax, bd.me[e]);
  }
  if (bd.Mmax == 0) { std::printf("all experts empty; nothing to measure\n"); return 1; }
  const char* mname = bd.mode == 0 ? "uniform"
                    : (bd.mode == 1 ? "ragged-coarse(multiples of TM: masked path NEVER entered)"
                                    : "skewed(arbitrary counts + zero-row experts)");
  std::printf("[lowbit-moe] %s  MOE_TK=%d  L=%d rows/expert=%d mode=%s N=%d K=%d gs=%d\n",
              PPU_CHUNK_STR, MOE_TK, bd.L, bd.Rows, mname, bd.N, bd.K, bd.gs);
  std::printf("             total=%d Mmax=%d Mmin=%d zero-row experts=%d active=%d  PEAK=%.0f TFLOP/s\n",
              bd.total, bd.Mmax, mn, zeros, bd.active, PEAK / 1e12);
  std::printf("             MFU is on the REAL rows (2*total*N*K), so wasting rows cannot buy MFU.\n");
  // The unit count is compiled in from the generator, so a silently shrunk enumeration shows up here rather than as a
  // quietly smaller sweep. Units whose shape is illegal (WarpM > TileM, or the delivery bound) compile to nothing and
  // print no rows, which is why this can exceed the number of sections that appear below.
  std::printf("             linked against %d generated sweep units (one per shape; illegal shapes print nothing)\n",
              MOE_UNIT_COUNT);
  if (moe_chunk_tally().off && moe_chunk_tally().on)
    std::printf("             *** SPLIT BRAIN: %d units built chunked, %d NOT -- the rows are not comparable ***\n",
                moe_chunk_tally().on, moe_chunk_tally().off);
  else
    std::printf("             all %d units agree: %s\n", moe_chunk_tally().on + moe_chunk_tally().off, PPU_CHUNK_STR);

  std::vector<half_t> hA((size_t)bd.total * bd.K), hSc((size_t)bd.L * bd.scale_k * bd.N),
                      hZr((size_t)bd.L * bd.scale_k * bd.N);
  for (size_t i = 0; i < hA.size(); ++i) hA[i] = half_t(0.01f);
  for (size_t i = 0; i < hSc.size(); ++i) { hSc[i] = half_t(0.0625f); hZr[i] = half_t(0.5f); }
  cutlass::DeviceAllocation<half_t> dA((size_t)bd.total * bd.K), dSc((size_t)bd.L * bd.scale_k * bd.N),
                                    dZr((size_t)bd.L * bd.scale_k * bd.N), dD((size_t)bd.total * bd.N);
  dA.copy_from_host(hA.data()); dSc.copy_from_host(hSc.data()); dZr.copy_from_host(hZr.data());

  bd.rsh.resize(bd.L);
  std::vector<half_t*> pdh(bd.L); std::vector<DStride> sdh(bd.L); std::vector<int> gmh(bd.L);
  for (int e = 0; e < bd.L; ++e) {
    bd.rsh[e] = cute::make_shape(bd.me[e], bd.N, bd.K); pdh[e] = dD.get() + (size_t)bd.offs[e] * bd.N;
    sdh[e] = cutlass::make_cute_packed_stride(DStride{}, cute::make_shape(bd.me[e], bd.N, 1)); gmh[e] = bd.me[e];
  }
  cutlass::DeviceAllocation<GS> rdev(bd.L);       rdev.copy_from_host(bd.rsh.data());
  cutlass::DeviceAllocation<half_t*> pd(bd.L);    pd.copy_from_host(pdh.data());
  cutlass::DeviceAllocation<DStride> sd(bd.L);    sd.copy_from_host(sdh.data());
  cutlass::DeviceAllocation<int> gm(bd.L);        gm.copy_from_host(gmh.data());
  cutlass::DeviceAllocation<int> offdev(bd.L);    offdev.copy_from_host(bd.offs.data());
  const size_t wsb = (size_t)cutlass::ceil_div(bd.Mmax,16)*cutlass::ceil_div(bd.N,64)*(size_t)bd.L*64;
  cutlass::DeviceAllocation<char> ws(wsb);
  bd.dA = dA.get(); bd.dSc = dSc.get(); bd.dZr = dZr.get();
  bd.rdev = rdev.get(); bd.pd = pd.get(); bd.sd = sd.get(); bd.gm = gm.get(); bd.offdev = offdev.get();
  bd.ws = ws.get(); bd.wsb = wsb;

  Best b2p{"",1e18}, b1p{"",1e18};
  moe_run_all(bd, b2p, b1p);

  std::printf("\n  ================= VERDICT =================\n");
  std::printf("  two-plane best : %-34s %8.2f us\n", b2p.tag, b2p.us);
  std::printf("  single-plane   : %-34s %8.2f us\n", b1p.tag, b1p.us);
  std::printf("  floor %%HBM is the COMPULSORY lower bound -- every byte crossing the bus at least once -- so it is\n");
  std::printf("  conclusive in ONE direction: low means NOT bandwidth-bound however much re-reading happens. noreuse is\n");
  std::printf("  ceil/floor, i.e. how much reuse the L2 must be supplying; it is a ratio, not a percentage, because the\n");
  std::printf("  first version of this printed 116-181%% of HBM and a bound looser than the peak measures nothing.\n");
  std::printf("  Then read mt and msk: smallest mt winning => the weight-bound rule holds; least msk => the dense\n");
  std::printf("  reasoning carries over; neither => the lever is occupancy and the next instrument is acu.\n");
  return 0;
}
