#!/usr/bin/env bash
# Qwen3.5-27B dense model benchmark wrapper.
#
# Source: Qwen/Qwen3.5-27B config/model card.
# Text config:
#   hidden=5120, layers=64, full-attn layers=16, linear-attn layers=48
#   linear-attn: q/k heads=16, v heads=48, head_dim=128
#   full-attn: q heads=24, kv heads=4, head_dim=256, attn_output_gate=true
#   dense FFN intermediate=17408, vocab=248320
#
# All GEMM/GEMV payloads in this wrapper use fp16.

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export MODEL_NAME="${MODEL_NAME:-Qwen3.5-27B}"
export HIDDEN_DIM="${HIDDEN_DIM:-5120}"
export LINEAR_DIM="${LINEAR_DIM:-10240}"
export LINEAR_Q_HEADS="${LINEAR_Q_HEADS:-16}"
export LINEAR_V_HEADS="${LINEAR_V_HEADS:-48}"
export LINEAR_HEAD_DIM="${LINEAR_HEAD_DIM:-128}"
export LINEAR_SMALL_PROJ_N="${LINEAR_SMALL_PROJ_N:-64}"

export W4A16_LINEAR_QKV_N="${W4A16_LINEAR_QKV_N:-10240}"
export W4A16_LINEAR_QKV_K="${W4A16_LINEAR_QKV_K:-5120}"
export W4A16_LINEAR_Z_N="${W4A16_LINEAR_Z_N:-6144}"
export W4A16_LINEAR_Z_K="${W4A16_LINEAR_Z_K:-5120}"
export W4A16_LINEAR_OUT_N="${W4A16_LINEAR_OUT_N:-5120}"
export W4A16_LINEAR_OUT_K="${W4A16_LINEAR_OUT_K:-6144}"

export FULL_ATTN_Q_HEADS="${FULL_ATTN_Q_HEADS:-24}"
export FULL_ATTN_KV_HEADS="${FULL_ATTN_KV_HEADS:-4}"
export FULL_ATTN_HEAD_DIM="${FULL_ATTN_HEAD_DIM:-256}"
export W4A16_FULL_ATTN_Q_PROJ_GATE_N="${W4A16_FULL_ATTN_Q_PROJ_GATE_N:-12288}"
export W4A16_FULL_ATTN_Q_PROJ_GATE_K="${W4A16_FULL_ATTN_Q_PROJ_GATE_K:-5120}"
export W4A16_FULL_ATTN_K_PROJ_N="${W4A16_FULL_ATTN_K_PROJ_N:-1024}"
export W4A16_FULL_ATTN_K_PROJ_K="${W4A16_FULL_ATTN_K_PROJ_K:-5120}"
export W4A16_FULL_ATTN_V_PROJ_N="${W4A16_FULL_ATTN_V_PROJ_N:-1024}"
export W4A16_FULL_ATTN_V_PROJ_K="${W4A16_FULL_ATTN_V_PROJ_K:-5120}"
export W4A16_FULL_ATTN_O_PROJ_N="${W4A16_FULL_ATTN_O_PROJ_N:-5120}"
export W4A16_FULL_ATTN_O_PROJ_K="${W4A16_FULL_ATTN_O_PROJ_K:-6144}"

export DENSE_FFN_INTERMEDIATE="${DENSE_FFN_INTERMEDIATE:-17408}"
export DENSE_FFN_GATE_N="${DENSE_FFN_GATE_N:-34816}"
export DENSE_FFN_GATE_K="${DENSE_FFN_GATE_K:-5120}"
export DENSE_FFN_DOWN_N="${DENSE_FFN_DOWN_N:-5120}"
export DENSE_FFN_DOWN_K="${DENSE_FFN_DOWN_K:-17408}"

export SAMPLING_VOCAB="${SAMPLING_VOCAB:-248320}"

export MODEL_LAYERS="${MODEL_LAYERS:-64}"
export MODEL_FULL_ATTN_LAYERS="${MODEL_FULL_ATTN_LAYERS:-16}"
export MODEL_LINEAR_ATTN_LAYERS="${MODEL_LINEAR_ATTN_LAYERS:-48}"
export MODEL_DENSE_FFN_LAYERS="${MODEL_DENSE_FFN_LAYERS:-64}"
export MODEL_MOE_FFN_LAYERS="${MODEL_MOE_FFN_LAYERS:-0}"

export ENABLE_LINEAR_ATTN=1
export ENABLE_FULL_ATTN=1
export ENABLE_DENSE_FFN=1
export ENABLE_MOE_FFN=0
export ENABLE_SHARED_EXPERT=0
export ENABLE_SAMPLING=1
export DECODE_CUBLAS_BACKEND="${DECODE_CUBLAS_BACKEND:-cuda_core}"
export QUANTIZED_GEMM_LABEL_KIND=dense

exec "$ROOT_DIR/run_all_qwen3.5-122B-A10B_GPTQ.sh" "$@"
