# Standalone gate for the MoE sweep unit GENERATOR, extracted from ../CMakeLists.txt.
#
# WHY IT EXISTS. The generator is CMake, and the bug it shipped could only be caught by CMake: `;` IS the list separator,
# so a WarpN list written "32;64" inside a row does not stay inside it -- foreach(IN LISTS) splits the row and the stray
# fragment has one field. A python mirror of the same table cannot see this, because python's split(';') has no such
# semantics; the mirror validated the enumeration and passed while the real configure died with six
# "list index out of range" errors per broken row.
#
# It also printed "128 generated units" while broken, because 8 malformed iterations x 16 equals the 5 correct formats
# x 16 -- the count that exists to catch a shrunken enumeration agreed with the right answer for the wrong reason.
#
#   run:  cmake -P gen_moe_units_check.cmake
#   negative control: change a "," back to ";" in a row and re-run; it must FATAL, and give it its OWN output dir --
#   the script starts with REMOVE_RECURSE, so running the broken variant into the same dir leaves the wreckage of a
#   half-generated tree that reads exactly like a real failure (this cost a round).
#
# Regenerate after editing the generator:
#   python3 - <<'"'"'PY'"'"'  ... see the session notes; it is a straight slice of CMakeLists.txt from set(_MOE_FORMATS)
#   to just before ppu_w4a16_executable(test_lowbit_moe_bench), with a binary-dir stub and the assertions appended.
set(CMAKE_CURRENT_BINARY_DIR "${CMAKE_CURRENT_LIST_DIR}/.moe_units_check")
file(REMOVE_RECURSE "${CMAKE_CURRENT_BINARY_DIR}")
set(_MOE_FORMATS
  "q3|1|uint2_t|uint1_t|2|1|64"
  "q5|1|int4_t|uint1_t|4|1|64"
  "q6|1|int4_t|uint2_t|4|2|32,64"
  "i2|0|uint2_t|half_t|2|0|32,64"
  "i4|0|int4_t|half_t|4|0|32,64"
)
set(_MOE_TM_LIST 32 64 128 256)
set(_MOE_TN_LIST 64 128)
set(_MOE_WM_LIST 32 64)

set(_MOE_UNIT_SRCS "")
set(_MOE_LAST_NM "")
set(_MOE_UNIT_DECLS "")
set(_MOE_UNIT_CALLS "")
set(_MOE_GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/moe_units")
file(MAKE_DIRECTORY "${_MOE_GEN_DIR}")
foreach(_row IN LISTS _MOE_FORMATS)
  string(REPLACE "|" ";" _f "${_row}")
  list(LENGTH _f _nf)
  if(NOT _nf EQUAL 7)
    message(FATAL_ERROR "_MOE_FORMATS row '${_row}' has ${_nf} fields, expected 7 "
                        "(name|2plane|lo_elem|hi_elem|lo_bits|hi_bits|WarpN,list). A ';' anywhere in a row splits it.")
  endif()
  list(GET _f 0 _nm)
  list(GET _f 1 _2p)
  list(GET _f 2 _lo)
  list(GET _f 3 _hi)
  list(GET _f 4 _lob)
  list(GET _f 5 _hib)
  list(GET _f 6 _wns)
  string(REPLACE "," ";" _wns "${_wns}")   # comma -> real CMake list, only now that the row is safely split
  foreach(_wn IN LISTS _wns)
    foreach(_tn IN LISTS _MOE_TN_LIST)
      foreach(_wm IN LISTS _MOE_WM_LIST)
        foreach(_tm IN LISTS _MOE_TM_LIST)
          set(_fn "moe_unit_${_nm}_tn${_tn}_wn${_wn}_tm${_tm}_wm${_wm}")
          set(_src "${_MOE_GEN_DIR}/${_fn}.cu")
          # CONFIGURE_DEPENDS is not needed: the content is a pure function of this loop, so a changed table means a
          # re-configure, and file(WRITE) leaves the timestamp alone when the bytes are identical... it does not, so
          # write through a compare to keep make from rebuilding all 128 units on every configure.
          file(WRITE "${_src}.in"
            "// GENERATED by CMakeLists.txt -- do not edit. One sweep unit = one shape, all stage counts.\n"
            "#define UNIT_NAME    ${_nm}\n"
            "#define UNIT_FN      ${_fn}\n"
            "#define UNIT_2PLANE  ${_2p}\n"
            "#define UNIT_LOELEM  ${_lo}\n"
            "#define UNIT_HIELEM  ${_hi}\n"
            "#define UNIT_LOB     ${_lob}\n"
            "#define UNIT_HIB     ${_hib}\n"
            "#define UNIT_TM      ${_tm}\n"
            "#define UNIT_TN      ${_tn}\n"
            "#define UNIT_WM      ${_wm}\n"
            "#define UNIT_WN      ${_wn}\n"
            "#include \"moe_bench_unit.inc\"\n")
          execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${_src}.in" "${_src}")
          list(APPEND _MOE_UNIT_SRCS "${_src}")
          set(_MOE_UNIT_DECLS "${_MOE_UNIT_DECLS}void ${_fn}(const Band&, Best&);\n")
          # A section header when the format changes, so 336 rows are still readable. Emitted by the generator rather
          # than by the units: only the generator knows the order they will be called in.
          if(NOT _nm STREQUAL _MOE_LAST_NM)
            set(_MOE_UNIT_CALLS "${_MOE_UNIT_CALLS}  std::printf(\"  --- ${_nm} ---\\n\");\n")
            set(_MOE_LAST_NM "${_nm}")
          endif()
          if(_2p)
            set(_MOE_UNIT_CALLS "${_MOE_UNIT_CALLS}  ${_fn}(bd, b2p);\n")
          else()
            set(_MOE_UNIT_CALLS "${_MOE_UNIT_CALLS}  ${_fn}(bd, b1p);\n")
          endif()
        endforeach()
      endforeach()
    endforeach()
  endforeach()
endforeach()
list(LENGTH _MOE_UNIT_SRCS _MOE_UNIT_N)
message(STATUS "MoE sweep: ${_MOE_UNIT_N} generated units in ${_MOE_GEN_DIR}")
# main() includes this instead of naming 128 functions by hand. PLAIN CODE, not a multi-line macro: that needs a trailing
# backslash on EVERY line and the first version emitted one, which would have been a build break generated by the build.
# MOE_UNIT_COUNT is compiled in so the binary prints how many units it was linked against -- a silently shrunk
# enumeration then shows up in the log instead of as a quietly smaller sweep.
file(WRITE "${_MOE_GEN_DIR}/moe_bench_units.inc.in"
     "// GENERATED by CMakeLists.txt -- do not edit.\n"
     "#define MOE_UNIT_COUNT ${_MOE_UNIT_N}\n"
     "${_MOE_UNIT_DECLS}"
     "static inline void moe_run_all(const Band& bd, Best& b2p, Best& b1p) {\n"
     "  (void)bd; (void)b2p; (void)b1p;\n"
     "${_MOE_UNIT_CALLS}"
     "}\n")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${_MOE_GEN_DIR}/moe_bench_units.inc.in" "${_MOE_GEN_DIR}/moe_bench_units.inc")

# -I must go through DEV_COMPILE_FLAGS, NOT target_include_directories: the device compiles are add_custom_commands that
# never see target properties (the same reason PPU_DEFS has to be forwarded twice). The generated units find the .inc via
# the custom command's own -I<source dir of the file>, but test_lowbit_moe_bench.cu lives in the source tree and would
# not find moe_bench_units.inc in the binary tree without this.

# assertions
file(GLOB _gen "${_MOE_GEN_DIR}/*.cu")
list(LENGTH _gen _ngen)
message(STATUS "generated .cu files on disk: ${_ngen}")
if(NOT _ngen EQUAL 128)
  message(FATAL_ERROR "expected 128 generated units, got ${_ngen}")
endif()
foreach(_bad q6_tn64_wn32 q6_tn64_wn64 i4_tn128_wn64 i2_tn64_wn32)
  file(GLOB _hit "${_MOE_GEN_DIR}/moe_unit_${_bad}_*.cu")
  list(LENGTH _hit _nh)
  if(NOT _nh EQUAL 8)
    message(FATAL_ERROR "moe_unit_${_bad}_* : expected 8 (TM x WM), got ${_nh}")
  endif()
endforeach()
file(GLOB _stray "${_MOE_GEN_DIR}/moe_unit_64_*.cu")
list(LENGTH _stray _nstray)
if(NOT _nstray EQUAL 0)
  message(FATAL_ERROR "the semicolon bug is back: ${_nstray} units named after a stray WarpN")
endif()
message(STATUS "OK: 128 units, both WarpN present for q6/i2/i4, no stray-format units")
