// L20 (step 1) -- replace the offline with one DERIVED from the layouts, and prove it bit-identical first.
//
// The five relayout steps plus the fold repack are ~500 lines of hand-written index arithmetic. That is where the
// K>256 bug lived, and it is regenerated by hand for every new format. L18 pinned down why any of it is needed:
//
//     the ONLY reason an offline relayout exists is that MixGemmEmit != identity.
//
// So the placement is derivable:  for each physical (row, word, bit) the chain says which logical (n,k) belongs
// there -- LogicalTV for the swzl, MixGemmEmit for the converter, pi = frag.layout()^-1, partition_B for the mma --
// and the offline is just that walk.
//
// HOW THIS IS MADE SAFE. Not by replacing anything: by producing the buffer independently and comparing it
// BYTE FOR BYTE against preprocess_weights_for_mixed_gemm (+ nfold_regroup_gmem where the config folds). If the two
// agree bit-identically on every configuration the tree uses, then swapping them is safe by construction rather
// than by argument. The five steps stay in place until the box regression is green.
//
// The one non-positional piece is int4's +8 from add_bias_and_interleave_int4s. A layout says where a code goes, not
// what it becomes, so the value transform is applied explicitly here.
//
//   nvcc -std=c++17 -Istub_inc -I../../../../third_party/actlize/include -I.. l20_derived_offline.cu -o l20 && ./l20
#include "cute/tensor.hpp"
#include "cute/atom/mma_atom.hpp"
#include "cutlass/numeric_types.h"
#include "cutlass/fast_numeric_conversion_for_mix_gemm.h"
#include "unfused_weight_dequantize.hpp"
#include <cstdio>
#include <vector>
using namespace cute;

struct F16Atom {};
namespace cute {
template <> struct MMA_Traits<F16Atom> {
  using ValTypeD=float; using ValTypeA=cutlass::half_t; using ValTypeB=cutlass::half_t; using ValTypeC=float;
  using Shape_MNK=Shape<_16,_16,_16>; using ThrID=Layout<_32>;
  using ALayout=Layout<Shape<Shape<_4,_8>,Shape<_2,_2,_2>>,Stride<Stride<_32,_1>,Stride<_16,_128,_8>>>;
  using BLayout=Layout<Shape<Shape<_4,_8>,Shape<_2,_2,_2>>,Stride<Stride<_32,_1>,Stride<_16,_128,_8>>>;
  using CLayout=Layout<Shape<Shape<_4,_8>,Shape<_4,_2>>,Stride<Stride<_16,_1>,Stride<_64,_8>>>;
};
}

// ---------------------------------------------------------------- the derived placement
// tile_map[(row*8 + wd)*CPW + j] = n_local*TK + k_local, over row in [0,Ng)
template <int Bits, int TM, int TN, int TK, int WM, int WN>
static std::vector<int> tile_map() {
  constexpr int WOM = TM/WM, WON = TN/WN, CPW = 32/Bits;
  constexpr int contig = TK*Bits/8, F = contig >= 32 ? 1 : 32/contig, Ng = TN/F;
  constexpr int RPI = WON*16, VEC = 4*32/Bits;
  using Mma = TiledMMA<MMA_Atom<F16Atom>, Layout<Shape<Int<WOM>,Int<WON>,_1>>,
                       Tile<Int<WOM*16>, Int<WON*16>, Int<TK>>>;
  auto sB = make_tensor(make_smem_ptr((cutlass::half_t*)nullptr),
                        make_layout(Shape<Int<TN>,Int<TK>>{}, Stride<Int<TK>,_1>{}));
  auto frag = Mma{}.get_thread_slice(0).partition_fragment_B(sB);
  const int NS = int(size(frag));
  // pi = frag.layout()^-1, and cute HAS this: right_inverse(Layout). It used to be a hand-rolled loop here (and in
  // seven sibling files); l30_should_have_been_cute.cu verifies the two agree on three shapes including int4's
  // production one. Worth replacing beyond tidiness: l20 is the file scheduled to become the production offline.
  auto pi = right_inverse(frag.layout());

  std::vector<int> m((size_t)Ng*8*CPW, -1);
  for (int t = 0; t < 32*WOM*WON; ++t) {
    const int lane = t%32, w = t/32, warp_n = w/WOM;
    auto part = Mma{}.get_thread_slice(t).partition_B(make_identity_tensor(make_shape(Int<TN>{},Int<TK>{})));
    for (int inst = 0; inst < Ng/RPI; ++inst)
      for (int v = 0; v < 4; ++v) {
        const int row = inst*RPI + 16*warp_n + (v/2)*8 + lane/4;
        const int wd  = (v%2)*4 + lane%4;
        for (int j = 0; j < CPW; ++j) {
          const int e = cutlass::MixGemmEmit<Bits>::index(j, v);
          const int flat = inst*VEC + e;
          if (flat < 0 || flat >= NS) continue;
          auto c = part(pi(flat));
          m[((size_t)row*8 + wd)*CPW + j] = int(get<0>(c))*TK + int(get<1>(c));
        }
      }
  }
  return m;
}

// write the buffer the kernel expects, straight from the tile map
template <int Bits, int TM, int TN, int TK, int WM, int WN>
static void place_derived(std::vector<int8_t>& out, const std::vector<int>& codes, int N, int K) {
  constexpr int CPW = 32/Bits, MASK = (1 << Bits) - 1;
  constexpr int contig = TK*Bits/8, F = contig >= 32 ? 1 : 32/contig, Ng = TN/F;
  const int kCon = 256, W_ROW_OFF = 256/CPW, RUNS = W_ROW_OFF/8;
  const int AiuByte = contig > 128 ? 128 : contig, AiuElem = AiuByte*8/Bits, RPS = kCon/AiuElem;
  auto m = tile_map<Bits,TM,TN,TK,WM,WN>();
  std::fill(out.begin(), out.end(), int8_t(0));
  const int nrow = N/F;
  for (int tn = 0; tn < N/TN; ++tn)
    for (int ki = 0; ki < K/TK; ++ki)
      for (int row = 0; row < Ng; ++row)
        for (int wd = 0; wd < 8; ++wd)
          for (int j = 0; j < CPW; ++j) {
            const int loc = m[((size_t)row*8 + wd)*CPW + j];
            if (loc < 0) continue;
            const int n = tn*TN + loc/TK, k = ki*TK + loc%TK;
            int val = codes[(size_t)n*K + k] & MASK;
            if (Bits == 4) val = (((int8_t)(val << 4) >> 4) + 8) & 0xF;   // add_bias_and_interleave_int4s
            size_t bitpos;
            if (F > 1) {                                       // folded: plane-major (l13)
              const int kb = ki/RUNS, t = ki%RUNS;
              bitpos = (size_t)((((size_t)kb*nrow + (size_t)tn*Ng + row)*W_ROW_OFF + t*8 + wd)*CPW + j)*Bits;
            } else {                                           // unfolded: interleave-256 direct (l16)
              bitpos = (size_t)((((size_t)(ki/RPS)*N + (size_t)tn*TN + row)*kCon
                                 + (ki%RPS)*AiuElem + wd*CPW + j))*Bits;
            }
            out[bitpos/8] |= int8_t(val << (bitpos%8));
          }
}

// ---------------------------------------------------------------- the existing offline, for comparison
template <int Bits, int TN, int TK>
static void place_shipped(std::vector<int8_t>& out, const std::vector<int>& codes, int N, int K) {
  constexpr int Bits_ = Bits, EPB = 8/Bits_, MASK = (1 << Bits) - 1;
  constexpr int contig = TK*Bits/8, F = contig >= 32 ? 1 : 32/contig;
  const auto qtc = Bits==1 ? QuantTypeClass::PACKED_INT1_WEIGHT_ONLY
                 : Bits==2 ? QuantTypeClass::PACKED_INT2_WEIGHT_ONLY
                           : QuantTypeClass::PACKED_INT4_WEIGHT_ONLY;
  // the caller's packing: qT[n*K+k] packed [N][K], k contiguous
  std::vector<int8_t> packed((size_t)N*K/EPB, 0);
  for (size_t i = 0; i < (size_t)N*K; ++i)
    packed[i/EPB] |= int8_t((codes[i] & MASK) << (Bits*(i%EPB)));
  std::vector<int8_t> pre(packed.size());
  preprocess_weights_for_mixed_gemm<false,256,0>(pre.data(), packed.data(), {(size_t)K,(size_t)N}, qtc);
  if (F > 1) { std::vector<int8_t> f(pre.size());
               nfold_regroup_gmem(f.data(), pre.data(), {(size_t)K,(size_t)N}, TN, TK, Bits); pre.swap(f); }
  out = pre;
}

template <int Bits, int TM, int TN, int TK, int WM, int WN>
static bool compare(const char* tag, int N, int K) {
  constexpr int Bits_ = Bits, EPB = 8/Bits_, MASK = (1 << Bits) - 1;
  constexpr int contig = TK*Bits/8, F = contig >= 32 ? 1 : 32/contig;
  std::vector<int> codes((size_t)N*K);
  for (size_t i = 0; i < codes.size(); ++i) codes[i] = int((i*2654435761u >> 7) & MASK);
  std::vector<int8_t> a((size_t)N*K/EPB), b;
  place_derived<Bits,TM,TN,TK,WM,WN>(a, codes, N, K);
  place_shipped<Bits,TN,TK>(b, codes, N, K);
  size_t diff = 0; for (size_t i = 0; i < a.size(); ++i) if (a[i] != b[i]) ++diff;
  printf("  %-26s int%d (%d,%d,%d) w%dx%d F=%d  %dx%d : %zu / %zu bytes differ  %s\n",
         tag, Bits, TM, TN, TK, WM, WN, F, N, K, diff, a.size(),
         diff ? "" : "<-- BIT-IDENTICAL");
  return diff == 0;
}

int main() {
  printf("L20 -- the derived offline vs the shipped one, byte for byte\n\n");
  bool ok = true;
  printf("  == fold configs\n");
  ok &= compare<1, 32, 128, 128, 32, 32>("int1 fold", 256, 512);
  ok &= compare<2, 64,  64,  64, 32, 32>("int2 fold", 256, 512);
  ok &= compare<2, 64, 128,  64, 32, 32>("int2 fold wideN", 256, 512);
  ok &= compare<4, 64,  64,  32, 32, 32>("int4 fold TK=32", 256, 512);
  printf("  == does the SHIPPED offline still match at WN=64? The offline is WN-independent (it only takes TN/TK/bits)\n");
  printf("     but the REQUIRED placement depends on WN through the fragment, so it can be right for only one WN.\n");
  ok &= compare<1, 32, 128, 128, 32, 64>("int1 TK128 WN=64", 256, 512);
  ok &= compare<1, 64, 128, 256, 32, 64>("int1 TK256 WN=64", 256, 512);
  printf("     => placement is WN-INVARIANT: pi and partition_B both move with MMA_N and the changes cancel.\n");
  printf("        So WN only changes the DELIVERY BOUND, not the required buffer. What forces a bit-granular packer\n");
  printf("        is TK: at int1/TK=64 a 32-bit word must carry two logical columns, which whole-word moves cannot do.\n");
  { std::vector<int> codes((size_t)256*512);
    for (size_t i = 0; i < codes.size(); ++i) codes[i] = int((i*2654435761u >> 7) & 1);
    std::vector<int8_t> a((size_t)256*512/8), b;
    place_derived<1,64,128,64,32,64>(a, codes, 256, 512);
    place_shipped<1,128,64>(b, codes, 256, 512);
    size_t d = 0; for (size_t i = 0; i < a.size(); ++i) if (a[i] != b[i]) ++d;
    printf("  int1 TK=64 WN=64 (needs bitpack)  256x512 : %zu / %zu bytes differ  %s\n", d, a.size(),
           d ? "<-- shipped offline CANNOT express it, as expected" : "<-- unexpectedly identical"); }
  printf("  == unfolded (F=1) configs, including int4's production shape\n");
  ok &= compare<4, 64,  64,  64, 32, 32>("int4 PRODUCTION", 128, 512);
  ok &= compare<2, 64,  64, 128, 32, 32>("int2 unfolded", 128, 512);
  ok &= compare<1, 64,  64, 256, 32, 32>("int1 unfolded", 128, 512);
  printf("\n  ALL: %s\n", ok ? "PASS -- the derived placement can replace the five steps by construction" : "FAIL");
  return ok ? 0 : 1;
}
